### PR TITLE
Dark mode

### LINKED ISSUE #1: Add dark mode

### PR DESCRIPTION
**Pull request by ghost**
Closes #1

### CODE REVIEW

**Comment by S-B99** [comment]
Could you please make this an option? Also the navbar colors are fucked in dark mode

**Review by 5HT2 — CHANGES_REQUESTED** [review]
Could you please make this an option? Also the navbar colors are fucked in dark mode

**Comment by ghost** [comment]
Closing since I don't believe it's necessary to implement this kind of state management in static documentation. If someone wants dark mode then they can install one of the many dark mode browser extensions, considering that adding this in-site would just make adding new things require more testing so that the colors are correct in dark mode, etc.

**Comment by 5HT2** [comment]
Honestly, that's a valid point

**Pull request closed without merging**
