### PR TITLE
fix 404 page :3

### PR DESCRIPTION
**Pull request by humboldt123**

### CODE REVIEW

**Comment by humboldt123** [comment]
LGTM!!!!

**Comment by DoctorBang** [comment]
We need this. It's necessary proof to show the world that Kami Blue is a rat. Or at least the website is.

**Comment by humboldt123** [comment]
commie blue dotorg slash backdoored 🙄

**Comment by DoctorBang** [comment]
That only deals with the client. We need proof that the website downloads malicious scripts.

**Comment by DoctorBang** [comment]
Sad

**Pull request closed without merging**
